### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shamansir** [shamansir/ielm#3]
## Before public

* [x] Get local coordinates for mouse movement in 3D viewer;
* [x] Tuples;
* [x] Records;
* [x] Arrays;
* [x] Ensure type aliases to work, may be also display the alias name;
* [x] Maybes, Results;
* [ ] Keyboard shortcuts in the interface; Ability to quickly switch Screens with some hotkey and/or number key;
* [x] Fix padding in errors texts; (#2)
* [x] Sets;
* [x] Controlling some function results with inputs (some code is already in the `Cell`/`Tryings`), also: https://ellie-app.com/jF6N5Ksxta1/4);
* [x] Collage viewers;
* [ ] Find a way to build in project directory instead of `build`. (#10)
* [ ] Support textures in 3D-viewer;
* [ ] Ensure both types of comments are supported;

## After public

* [x] Union Types;
* [ ] Color, Dates, Time;
* [ ] Plots for some functions;
* [x] `raw` viewer for those types which are usually wrapped in 3dViewer or wrapped with inputs, if user wants to see them in their pureness instead;
* [ ] X/Y/Z vectors for 3dViewer;
* [x] The ability to add more screens;
* [x] Tabs should display the condition of the code (Outdated vs Compiling vs Compiled/Up-to-date);
* [ ] Expose only required things from all used or generated Elm modules;
* [ ] Add ability to avoid specifying perspective when using default shader;
* [ ] Do not include duplicate imports in `Screen` files;
* [ ] Try [Elm examples from Exercism](http://exercism.io/languages/elm/exercises);

## Long stretch goals

* [ ] Tasks;
* [ ] Cmds and Msgs;
* [ ] Test other kinds of "Apps" (not Maybe/Result, custom types);
* [ ] Zoom, reset position and some other pretty options for 3D-viewer;
* [ ] Better error display (show cell and highlight corresponding line);
* [ ] Listen for mouse movement only if Cell has 3DViewer inside;
* [ ] Consider other ways of choosing a version of new Screen (i.e. use hash numbers or milliseconds for versioning);
* [ ] Processes;
* [ ] `node-elm-repl` [parsing issues](https://github.com/shamansir/node-elm-repl/issues?q=is%3Aissue+is%3Aopen+label%3Abug)
